defaults: &defaults
  server:
    interfaces:
      - { protocol: udp, addr: 0.0.0.0, port: 5300 }
  resolvers:
    - name: google
      servers:
        - { protocol: udp, addr: 8.8.8.8, port: 53 }
        - { protocol: udp, addr: 8.8.4.4, port: 53 }
      sequence_max: 65536
    - name: mosaic
      servers:
        - { protocol: udp, addr: 8.8.8.8, port: 53 }
      sequence_max: 65536
  default_resolver: google
  matchers:
    - expression: '0\.0\.8\.1\.tnsi\.com$'
      resolver: mosaic
      question_matcher: '(.*)\.tnsi\.com$'
      question_template: '${match}.mosaic.nrd.tnsi.com'
      answer_substitutions:
        'spid': cic
        'npdi': foof
    - expression: '\.tnsi\.com$'
      resolver: mosaic
      question_matcher: '(.*)\.tnsi\.com$'
      question_template: '${match}.mosaic.nrd.tnsi.com'
      answer_substitutions:
        'spid': cic
        'npdi': foof
  log: /home/klarrimore/Projects/dnsserver/tmp/logs/server.log

development:
  <<: *defaults
  log_level: debug

test:
  <<: *defaults
  log_level: debug

production:
  <<: *defaults
  log_level: info
